// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: cart.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addCartItem = `-- name: AddCartItem :one
INSERT INTO cart_items (cart_id, sku_id, quantity)
VALUES ($1, $2, $3)
ON CONFLICT (cart_id, sku_id)
DO UPDATE SET quantity = cart_items.quantity + EXCLUDED.quantity,
              updated_at = now()
WHERE cart_items.quantity + EXCLUDED.quantity <= 99
RETURNING quantity
`

type AddCartItemParams struct {
	CartID   uuid.UUID `json:"cart_id"`
	SkuID    uuid.UUID `json:"sku_id"`
	Quantity int32     `json:"quantity"`
}

func (q *Queries) AddCartItem(ctx context.Context, arg AddCartItemParams) (int32, error) {
	row := q.db.QueryRow(ctx, addCartItem, arg.CartID, arg.SkuID, arg.Quantity)
	var quantity int32
	err := row.Scan(&quantity)
	return quantity, err
}

const countCartItems = `-- name: CountCartItems :one
SELECT count(*) FROM cart_items WHERE cart_id = $1
`

func (q *Queries) CountCartItems(ctx context.Context, cartID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCartItems, cartID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrGetActiveCart = `-- name: CreateOrGetActiveCart :one
INSERT INTO carts (id, user_id)
VALUES ($1, $2)
ON CONFLICT (user_id) WHERE status = 'active'
DO UPDATE SET updated_at = now()
RETURNING id
`

type CreateOrGetActiveCartParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) CreateOrGetActiveCart(ctx context.Context, arg CreateOrGetActiveCartParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createOrGetActiveCart, arg.ID, arg.UserID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getActiveCartItemsByUser = `-- name: GetActiveCartItemsByUser :many
SELECT ci.sku_id, ci.quantity
FROM carts AS c
JOIN cart_items AS ci ON ci.cart_id = c.id
WHERE c.user_id = $1 AND c.status = 'active'
ORDER BY ci.created_at, ci.sku_id
`

type GetActiveCartItemsByUserRow struct {
	SkuID    uuid.UUID `json:"sku_id"`
	Quantity int32     `json:"quantity"`
}

func (q *Queries) GetActiveCartItemsByUser(ctx context.Context, userID uuid.UUID) ([]GetActiveCartItemsByUserRow, error) {
	rows, err := q.db.Query(ctx, getActiveCartItemsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetActiveCartItemsByUserRow{}
	for rows.Next() {
		var i GetActiveCartItemsByUserRow
		if err := rows.Scan(&i.SkuID, &i.Quantity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeCartItem = `-- name: RemoveCartItem :exec
DELETE FROM cart_items
WHERE sku_id = $2
  AND cart_id = (SELECT id FROM carts WHERE user_id = $1 AND status = 'active')
`

type RemoveCartItemParams struct {
	UserID uuid.UUID `json:"user_id"`
	SkuID  uuid.UUID `json:"sku_id"`
}

func (q *Queries) RemoveCartItem(ctx context.Context, arg RemoveCartItemParams) error {
	_, err := q.db.Exec(ctx, removeCartItem, arg.UserID, arg.SkuID)
	return err
}

const setCartItemQuantity = `-- name: SetCartItemQuantity :one
UPDATE cart_items
SET quantity = $3, updated_at = now()
WHERE sku_id = $2
  AND cart_id = (SELECT id FROM carts WHERE user_id = $1 AND status = 'active')
RETURNING quantity
`

type SetCartItemQuantityParams struct {
	UserID   uuid.UUID `json:"user_id"`
	SkuID    uuid.UUID `json:"sku_id"`
	Quantity int32     `json:"quantity"`
}

func (q *Queries) SetCartItemQuantity(ctx context.Context, arg SetCartItemQuantityParams) (int32, error) {
	row := q.db.QueryRow(ctx, setCartItemQuantity, arg.UserID, arg.SkuID, arg.Quantity)
	var quantity int32
	err := row.Scan(&quantity)
	return quantity, err
}
