// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: catalog.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countProducts = `-- name: CountProducts :one
SELECT count(*) FROM products
`

func (q *Queries) CountProducts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countProducts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (id, name, slug, description)
VALUES ($1, $2, $3, $4)
RETURNING id, name, slug, description, created_at, updated_at
`

type CreateProductParams struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Slug        string    `json:"slug"`
	Description string    `json:"description"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Description,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSKU = `-- name: CreateSKU :one
INSERT INTO skus (id, product_id, code, price_cents, currency)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, product_id, code, price_cents, currency, created_at, updated_at
`

type CreateSKUParams struct {
	ID         uuid.UUID `json:"id"`
	ProductID  uuid.UUID `json:"product_id"`
	Code       string    `json:"code"`
	PriceCents int64     `json:"price_cents"`
	Currency   string    `json:"currency"`
}

func (q *Queries) CreateSKU(ctx context.Context, arg CreateSKUParams) (Sku, error) {
	row := q.db.QueryRow(ctx, createSKU,
		arg.ID,
		arg.ProductID,
		arg.Code,
		arg.PriceCents,
		arg.Currency,
	)
	var i Sku
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Code,
		&i.PriceCents,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductBySlug = `-- name: GetProductBySlug :one
SELECT id, name, slug, description, created_at, updated_at
FROM products
WHERE slug = $1
`

func (q *Queries) GetProductBySlug(ctx context.Context, slug string) (Product, error) {
	row := q.db.QueryRow(ctx, getProductBySlug, slug)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, name, slug, description, created_at, updated_at
FROM products
ORDER BY created_at DESC, id DESC
LIMIT $1 OFFSET $2
`

type ListProductsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSKUsByProductIDs = `-- name: ListSKUsByProductIDs :many
SELECT id, product_id, code, price_cents, currency, created_at, updated_at
FROM skus
WHERE product_id = ANY($1::uuid[])
ORDER BY product_id, code ASC
`

func (q *Queries) ListSKUsByProductIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]Sku, error) {
	rows, err := q.db.Query(ctx, listSKUsByProductIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Sku{}
	for rows.Next() {
		var i Sku
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Code,
			&i.PriceCents,
			&i.Currency,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
