// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: identity.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, user_id, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, token_hash, expires_at, revoked_at, created_at
`

type CreateSessionParams struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash []byte             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email, normalized_email, password_hash, display_name)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, normalized_email, password_hash, display_name, status, created_at, updated_at
`

type CreateUserParams struct {
	ID              uuid.UUID `json:"id"`
	Email           string    `json:"email"`
	NormalizedEmail string    `json:"normalized_email"`
	PasswordHash    string    `json:"password_hash"`
	DisplayName     string    `json:"display_name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.NormalizedEmail,
		arg.PasswordHash,
		arg.DisplayName,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.NormalizedEmail,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByActiveSession = `-- name: GetUserByActiveSession :one
SELECT u.id, u.email, u.display_name, u.status, u.created_at, u.updated_at
FROM sessions AS s
JOIN users AS u ON u.id = s.user_id
WHERE s.token_hash = $1
  AND s.revoked_at IS NULL
  AND s.expires_at > $2
  AND u.status = 'active'
`

type GetUserByActiveSessionParams struct {
	TokenHash []byte             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type GetUserByActiveSessionRow struct {
	ID          uuid.UUID          `json:"id"`
	Email       string             `json:"email"`
	DisplayName string             `json:"display_name"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByActiveSession(ctx context.Context, arg GetUserByActiveSessionParams) (GetUserByActiveSessionRow, error) {
	row := q.db.QueryRow(ctx, getUserByActiveSession, arg.TokenHash, arg.ExpiresAt)
	var i GetUserByActiveSessionRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserCredentialByNormalizedEmail = `-- name: GetUserCredentialByNormalizedEmail :one
SELECT id, email, normalized_email, password_hash, display_name, status, created_at, updated_at
FROM users
WHERE normalized_email = $1
`

func (q *Queries) GetUserCredentialByNormalizedEmail(ctx context.Context, normalizedEmail string) (User, error) {
	row := q.db.QueryRow(ctx, getUserCredentialByNormalizedEmail, normalizedEmail)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.NormalizedEmail,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions
SET revoked_at = $2
WHERE token_hash = $1
  AND revoked_at IS NULL
`

type RevokeSessionParams struct {
	TokenHash []byte             `json:"token_hash"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) error {
	_, err := q.db.Exec(ctx, revokeSession, arg.TokenHash, arg.RevokedAt)
	return err
}
